# Generated by Django 5.0.4 on 2024-04-16 11:50

import contacts.models
import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='start', max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=20)),
                ('contact', models.ForeignKey(default=contacts.models.Contact, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('product', models.ForeignKey(default=products.models.Product, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
